### PR TITLE
allow to create sequence without gap

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by jssuzanne** [comment]
You should modify also the **column.Sequence** https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1153

- [ ] save if the column must be have gap : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1179

- [ ] Update autodoc to display the gap value : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1188

- [ ] Pass the options to Sequence.insert method : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1206

**Comment by petrus-v** [comment]
> You should modify also the **column.Sequence** https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1153
> 
>     * [ ]  save if the column must be have gap : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1179
> 
>     * [ ]  Update autodoc to display the gap value : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1188
> 
>     * [ ]  Pass the options to Sequence.insert method : https://github.com/AnyBlok/AnyBlok/blob/master/anyblok/column.py#L1206

Thanks for hints I'll improve those points

**Comment by petrus-v** [comment]
As discussed earlier, I've created issue #153 from your comment and starts PR #154 to makes clear the transaction issue to properly manage Sequence column with no_gap flag.

**Review by jssuzanne — APPROVED** [review]
Thanks for your PR

**Pull request merged**
